

def ligth_scss(nameStyle):
    return """//  This file is autogenerated, do not modify manually
@import "../../bulma/sass/utilities/_all.sass";
@import "1.{nameStyle}.light.custom.scss";  
@import "../../bulma/bulma.sass";""")  
 

