from os import system as s #this file is autogenerated
s("sass purple.light.scss ../../css/purple.light.css --style compressed")
s("sass purple.dark.scss  ../../css/purple.dark.css --style compressed")