from os import system as s #this file is autogenerated
s("sass edwinn.light.scss ../../css/edwinn.light.css --style compressed")
s("sass edwinn.dark.scss  ../../css/edwinn.dark.css --style compressed")