from os import system as s #this file is autogenerated
s("sass school.light.scss ../../css/school.light.css --style compressed")
s("sass school.dark.scss  ../../css/school.dark.css --style compressed")