from os import system as s #this file is autogenerated
s("sass monoDark.light.scss ../../css/monoDark.light.css --style compressed")
s("sass monoDark.dark.scss  ../../css/monoDark.dark.css --style compressed")