from os import system as s #this file is autogenerated
s("sass default.light.scss ../../css/default.light.css --style compressed")
s("sass default.dark.scss  ../../css/default.dark.css --style compressed")