from os import system as s #this file is autogenerated
s("sass darkred.light.scss ../../css/darkred.light.css --style compressed")
s("sass darkred.dark.scss  ../../css/darkred.dark.css --style compressed")